openapi: 3.1.0
info:
  contact:
    email: cmdi@clarin.eu
    name: CLARIN ERIC
    url: https://www.clarin.eu
  description: Components and profiles registry for the Component Metadata Infrastructure
  title: Component Registry API
  version: "1.0"
servers:
- description: Generated server url
  url: http://localhost:8080/rest
tags:
- description: Components and profiles as items (common data model)
  name: Items
- description: Registry of components and profiles
  name: Components and profiles
paths:
  /registry/profiles:
    get:
      operationId: getProfiles
      parameters:
      - explode: true
        in: query
        name: status
        required: true
        schema:
          items:
            enum:
            - development
            - production
            - deprecated
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: sortBy
        required: false
        schema:
          default: name
          type: string
        style: form
      - explode: true
        in: query
        name: sortDirection
        required: false
        schema:
          default: ASC
          enum:
          - ASC
          - DESC
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfilesList"
            application/xml:
              schema:
                $ref: "#/components/schemas/ProfilesList"
          description: OK
      tags:
      - Components and profiles
      x-accepts:
      - application/json
      - application/xml
  /registry/profiles/{componentId}/description:
    get:
      operationId: getProfileItem
      parameters:
      - explode: false
        in: path
        name: componentId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileDescription"
            application/xml:
              schema:
                $ref: "#/components/schemas/ProfileDescription"
          description: OK
      tags:
      - Components and profiles
      x-accepts:
      - application/json
      - application/xml
  /registry/items:
    get:
      operationId: getItems
      parameters:
      - explode: true
        in: query
        name: type
        required: false
        schema:
          enum:
          - COMPONENT
          - PROFILE
          type: string
        style: form
      - explode: true
        in: query
        name: status
        required: false
        schema:
          items:
            enum:
            - development
            - production
            - deprecated
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: sortBy
        required: false
        schema:
          default: name
          type: string
        style: form
      - explode: true
        in: query
        name: sortDirection
        required: false
        schema:
          default: ASC
          enum:
          - ASC
          - DESC
          type: string
        style: form
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/BaseDescription"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/BaseDescription"
                type: array
          description: A list of items that meet the filter criteria (if applicable)
      summary: Get a filtered list of descriptions of profiles and/or components
      tags:
      - Items
      x-accepts:
      - application/json
      - application/xml
  /registry/items/{componentId}:
    get:
      operationId: getItem
      parameters:
      - explode: false
        in: path
        name: componentId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/BaseDescription"
            application/json:
              schema:
                $ref: "#/components/schemas/BaseDescription"
          description: A description of the identified item
        "404":
          description: Item not found
      summary: Get the description of a profile or component
      tags:
      - Items
      x-accepts:
      - application/json
      - application/xml
  /registry/items/{componentId}/spec:
    get:
      operationId: getItemSpec
      parameters:
      - explode: false
        in: path
        name: componentId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Accept
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/ComponentSpec"
            application/json:
              schema:
                $ref: "#/components/schemas/ComponentSpec"
          description: |
            The component specification of the identified item.
            The JSON representation is derived from the primary
            specification which is stored as XML.
        "404":
          description: Item not found
      summary: Get the specification for the profile or component
      tags:
      - Items
      x-accepts:
      - application/json
      - application/xml
  /registry/components:
    get:
      operationId: getComponents
      parameters:
      - explode: true
        in: query
        name: status
        required: true
        schema:
          items:
            enum:
            - development
            - production
            - deprecated
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: sortBy
        required: false
        schema:
          default: name
          type: string
        style: form
      - explode: true
        in: query
        name: sortDirection
        required: false
        schema:
          default: ASC
          enum:
          - ASC
          - DESC
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComponentsList"
            application/xml:
              schema:
                $ref: "#/components/schemas/ComponentsList"
          description: OK
      tags:
      - Components and profiles
      x-accepts:
      - application/json
      - application/xml
  /registry/components/{componentId}/description:
    get:
      operationId: getComponentItem
      parameters:
      - explode: false
        in: path
        name: componentId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComponentDescription"
            application/xml:
              schema:
                $ref: "#/components/schemas/ComponentDescription"
          description: OK
      tags:
      - Components and profiles
      x-accepts:
      - application/json
      - application/xml
components:
  schemas:
    ProfileDescription:
      example:
        successor: successor
        creatorName: creatorName
        description: description
        derivedfrom: derivedfrom
        userId: userId
        recommended: true
        groupName: groupName
        public: true
        commentsCount: 0
        domainName: domainName
        name: name
        registrationDate: 2000-01-23T04:56:07.000+00:00
        isPublic: true
        href: href
        id: id
        showInEditor: true
        status: development
      properties:
        name:
          type: string
        description:
          type: string
        registrationDate:
          format: date-time
          type: string
        creatorName:
          type: string
        userId:
          type: string
        domainName:
          type: string
        href:
          type: string
          xml:
            namespace: http://www.w3.org/1999/xlink
        groupName:
          type: string
        status:
          enum:
          - development
          - production
          - deprecated
          type: string
        derivedfrom:
          type: string
        successor:
          type: string
        commentsCount:
          format: int32
          type: integer
        recommended:
          type: boolean
        showInEditor:
          type: boolean
        public:
          type: boolean
        id:
          type: string
        isPublic:
          type: boolean
      xml:
        name: profileDescription
    ProfilesList:
      example:
        components:
        - successor: successor
          creatorName: creatorName
          description: description
          derivedfrom: derivedfrom
          userId: userId
          recommended: true
          groupName: groupName
          public: true
          commentsCount: 0
          domainName: domainName
          name: name
          registrationDate: 2000-01-23T04:56:07.000+00:00
          isPublic: true
          href: href
          id: id
          showInEditor: true
          status: development
        - successor: successor
          creatorName: creatorName
          description: description
          derivedfrom: derivedfrom
          userId: userId
          recommended: true
          groupName: groupName
          public: true
          commentsCount: 0
          domainName: domainName
          name: name
          registrationDate: 2000-01-23T04:56:07.000+00:00
          isPublic: true
          href: href
          id: id
          showInEditor: true
          status: development
      properties:
        components:
          items:
            $ref: "#/components/schemas/ProfileDescription"
          type: array
    BaseDescription:
      example:
        successor: successor
        creatorName: creatorName
        description: description
        derivedfrom: derivedfrom
        userId: userId
        recommended: true
        groupName: groupName
        public: true
        commentsCount: 0
        domainName: domainName
        name: name
        registrationDate: 2000-01-23T04:56:07.000+00:00
        isPublic: true
        href: href
        id: id
        showInEditor: true
        status: development
      properties:
        name:
          type: string
        description:
          type: string
        registrationDate:
          format: date-time
          type: string
        creatorName:
          type: string
        userId:
          type: string
        domainName:
          type: string
        href:
          type: string
          xml:
            namespace: http://www.w3.org/1999/xlink
        groupName:
          type: string
        status:
          enum:
          - development
          - production
          - deprecated
          type: string
        derivedfrom:
          type: string
        successor:
          type: string
        commentsCount:
          format: int32
          type: integer
        recommended:
          type: boolean
        public:
          type: boolean
        id:
          type: string
        showInEditor:
          type: boolean
        isPublic:
          type: boolean
      xml:
        name: description
    Attribute:
      example:
        conceptLink: conceptLink
        valueScheme: BOOLEAN
        documentation:
        - lang: lang
          value: value
        - lang: lang
          value: value
        name: name
        attributeValueScheme:
          vocabulary:
            valueLanguage: valueLanguage
            enumeration:
              item:
              - conceptLink: conceptLink
                appInfo: appInfo
                value: value
                otherAttributes:
                  key: otherAttributes
              - conceptLink: conceptLink
                appInfo: appInfo
                value: value
                otherAttributes:
                  key: otherAttributes
              appinfo: appinfo
            uri: uri
            valueProperty: valueProperty
          pattern: pattern
        otherAttributes:
          key: otherAttributes
        required: true
        autoValue:
        - autoValue
        - autoValue
      properties:
        documentation:
          items:
            $ref: "#/components/schemas/DocumentationType"
          type: array
          xml:
            name: Documentation
        attributeValueScheme:
          $ref: "#/components/schemas/ValueSchemeType"
        autoValue:
          items:
            type: string
            xml:
              name: AutoValue
          type: array
          xml:
            name: AutoValue
        name:
          type: string
          xml:
            attribute: true
        conceptLink:
          type: string
          xml:
            attribute: true
            name: ConceptLink
        valueScheme:
          enum:
          - BOOLEAN
          - DECIMAL
          - FLOAT
          - INT
          - STRING
          - ANY_URI
          - DATE
          - G_DAY
          - G_MONTH
          - G_YEAR
          - TIME
          - DATE_TIME
          type: string
          xml:
            attribute: true
            name: ValueScheme
        required:
          type: boolean
          xml:
            attribute: true
            name: Required
        otherAttributes:
          additionalProperties:
            type: string
    AttributeListType:
      example:
        attribute:
        - conceptLink: conceptLink
          valueScheme: BOOLEAN
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          name: name
          attributeValueScheme:
            vocabulary:
              valueLanguage: valueLanguage
              enumeration:
                item:
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                appinfo: appinfo
              uri: uri
              valueProperty: valueProperty
            pattern: pattern
          otherAttributes:
            key: otherAttributes
          required: true
          autoValue:
          - autoValue
          - autoValue
        - conceptLink: conceptLink
          valueScheme: BOOLEAN
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          name: name
          attributeValueScheme:
            vocabulary:
              valueLanguage: valueLanguage
              enumeration:
                item:
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                appinfo: appinfo
              uri: uri
              valueProperty: valueProperty
            pattern: pattern
          otherAttributes:
            key: otherAttributes
          required: true
          autoValue:
          - autoValue
          - autoValue
      properties:
        attribute:
          items:
            $ref: "#/components/schemas/Attribute"
          type: array
          xml:
            name: Attribute
      required:
      - attribute
    ComponentSpec:
      example:
        isProfile: true
        cmdoriginalVersion: cmdoriginalVersion
        component:
          component:
          - null
          - null
          conceptLink: conceptLink
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          attributeList:
            attribute:
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
          name: name
          componentRef: componentRef
          cardinalityMin:
          - cardinalityMin
          - cardinalityMin
          cardinalityMax:
          - cardinalityMax
          - cardinalityMax
          otherAttributes:
            key: otherAttributes
          element:
          - conceptLink: conceptLink
            valueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            attributeList:
              attribute:
              - conceptLink: conceptLink
                valueScheme: BOOLEAN
                documentation:
                - lang: lang
                  value: value
                - lang: lang
                  value: value
                name: name
                attributeValueScheme:
                  vocabulary:
                    valueLanguage: valueLanguage
                    enumeration:
                      item:
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      appinfo: appinfo
                    uri: uri
                    valueProperty: valueProperty
                  pattern: pattern
                otherAttributes:
                  key: otherAttributes
                required: true
                autoValue:
                - autoValue
                - autoValue
              - conceptLink: conceptLink
                valueScheme: BOOLEAN
                documentation:
                - lang: lang
                  value: value
                - lang: lang
                  value: value
                name: name
                attributeValueScheme:
                  vocabulary:
                    valueLanguage: valueLanguage
                    enumeration:
                      item:
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      appinfo: appinfo
                    uri: uri
                    valueProperty: valueProperty
                  pattern: pattern
                otherAttributes:
                  key: otherAttributes
                required: true
                autoValue:
                - autoValue
                - autoValue
            name: name
            cardinalityMin:
            - cardinalityMin
            - cardinalityMin
            valueSchemeAttribute: BOOLEAN
            cardinalityMax:
            - cardinalityMax
            - cardinalityMax
            otherAttributes:
              key: otherAttributes
            multilingual: true
            autoValue:
            - autoValue
            - autoValue
          - conceptLink: conceptLink
            valueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            attributeList:
              attribute:
              - conceptLink: conceptLink
                valueScheme: BOOLEAN
                documentation:
                - lang: lang
                  value: value
                - lang: lang
                  value: value
                name: name
                attributeValueScheme:
                  vocabulary:
                    valueLanguage: valueLanguage
                    enumeration:
                      item:
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      appinfo: appinfo
                    uri: uri
                    valueProperty: valueProperty
                  pattern: pattern
                otherAttributes:
                  key: otherAttributes
                required: true
                autoValue:
                - autoValue
                - autoValue
              - conceptLink: conceptLink
                valueScheme: BOOLEAN
                documentation:
                - lang: lang
                  value: value
                - lang: lang
                  value: value
                name: name
                attributeValueScheme:
                  vocabulary:
                    valueLanguage: valueLanguage
                    enumeration:
                      item:
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      - conceptLink: conceptLink
                        appInfo: appInfo
                        value: value
                        otherAttributes:
                          key: otherAttributes
                      appinfo: appinfo
                    uri: uri
                    valueProperty: valueProperty
                  pattern: pattern
                otherAttributes:
                  key: otherAttributes
                required: true
                autoValue:
                - autoValue
                - autoValue
            name: name
            cardinalityMin:
            - cardinalityMin
            - cardinalityMin
            valueSchemeAttribute: BOOLEAN
            cardinalityMax:
            - cardinalityMax
            - cardinalityMax
            otherAttributes:
              key: otherAttributes
            multilingual: true
            autoValue:
            - autoValue
            - autoValue
          base: base
        header:
          successor: successor
          name: name
          derivedFrom: derivedFrom
          description: description
          id: id
          statusComment: statusComment
          status: status
        cmdversion: cmdversion
      properties:
        header:
          $ref: "#/components/schemas/Header"
        component:
          $ref: "#/components/schemas/ComponentType"
        isProfile:
          type: boolean
          xml:
            attribute: true
        cmdversion:
          type: string
        cmdoriginalVersion:
          type: string
      required:
      - component
      - header
      xml:
        name: ComponentSpec
    ComponentType:
      example:
        component:
        - null
        - null
        conceptLink: conceptLink
        documentation:
        - lang: lang
          value: value
        - lang: lang
          value: value
        attributeList:
          attribute:
          - conceptLink: conceptLink
            valueScheme: BOOLEAN
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            name: name
            attributeValueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            otherAttributes:
              key: otherAttributes
            required: true
            autoValue:
            - autoValue
            - autoValue
          - conceptLink: conceptLink
            valueScheme: BOOLEAN
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            name: name
            attributeValueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            otherAttributes:
              key: otherAttributes
            required: true
            autoValue:
            - autoValue
            - autoValue
        name: name
        componentRef: componentRef
        cardinalityMin:
        - cardinalityMin
        - cardinalityMin
        cardinalityMax:
        - cardinalityMax
        - cardinalityMax
        otherAttributes:
          key: otherAttributes
        element:
        - conceptLink: conceptLink
          valueScheme:
            vocabulary:
              valueLanguage: valueLanguage
              enumeration:
                item:
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                appinfo: appinfo
              uri: uri
              valueProperty: valueProperty
            pattern: pattern
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          attributeList:
            attribute:
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
          name: name
          cardinalityMin:
          - cardinalityMin
          - cardinalityMin
          valueSchemeAttribute: BOOLEAN
          cardinalityMax:
          - cardinalityMax
          - cardinalityMax
          otherAttributes:
            key: otherAttributes
          multilingual: true
          autoValue:
          - autoValue
          - autoValue
        - conceptLink: conceptLink
          valueScheme:
            vocabulary:
              valueLanguage: valueLanguage
              enumeration:
                item:
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                - conceptLink: conceptLink
                  appInfo: appInfo
                  value: value
                  otherAttributes:
                    key: otherAttributes
                appinfo: appinfo
              uri: uri
              valueProperty: valueProperty
            pattern: pattern
          documentation:
          - lang: lang
            value: value
          - lang: lang
            value: value
          attributeList:
            attribute:
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
            - conceptLink: conceptLink
              valueScheme: BOOLEAN
              documentation:
              - lang: lang
                value: value
              - lang: lang
                value: value
              name: name
              attributeValueScheme:
                vocabulary:
                  valueLanguage: valueLanguage
                  enumeration:
                    item:
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    - conceptLink: conceptLink
                      appInfo: appInfo
                      value: value
                      otherAttributes:
                        key: otherAttributes
                    appinfo: appinfo
                  uri: uri
                  valueProperty: valueProperty
                pattern: pattern
              otherAttributes:
                key: otherAttributes
              required: true
              autoValue:
              - autoValue
              - autoValue
          name: name
          cardinalityMin:
          - cardinalityMin
          - cardinalityMin
          valueSchemeAttribute: BOOLEAN
          cardinalityMax:
          - cardinalityMax
          - cardinalityMax
          otherAttributes:
            key: otherAttributes
          multilingual: true
          autoValue:
          - autoValue
          - autoValue
        base: base
      properties:
        documentation:
          items:
            $ref: "#/components/schemas/DocumentationType"
          type: array
          xml:
            name: Documentation
        attributeList:
          $ref: "#/components/schemas/AttributeListType"
        element:
          items:
            $ref: "#/components/schemas/ElementType"
          type: array
          xml:
            name: Element
        component:
          items:
            $ref: "#/components/schemas/ComponentType"
          type: array
          xml:
            name: Component
        name:
          type: string
          xml:
            attribute: true
        componentRef:
          type: string
          xml:
            attribute: true
            name: ComponentRef
        conceptLink:
          type: string
          xml:
            attribute: true
            name: ConceptLink
        cardinalityMin:
          items:
            type: string
          type: array
          xml:
            attribute: true
            name: CardinalityMin
        cardinalityMax:
          items:
            type: string
          type: array
          xml:
            attribute: true
            name: CardinalityMax
        base:
          type: string
          xml:
            attribute: true
            namespace: http://www.w3.org/XML/1998/namespace
        otherAttributes:
          additionalProperties:
            type: string
    DocumentationType:
      example:
        lang: lang
        value: value
      properties:
        value:
          type: string
        lang:
          type: string
          xml:
            attribute: true
            namespace: http://www.w3.org/XML/1998/namespace
    ElementType:
      example:
        conceptLink: conceptLink
        valueScheme:
          vocabulary:
            valueLanguage: valueLanguage
            enumeration:
              item:
              - conceptLink: conceptLink
                appInfo: appInfo
                value: value
                otherAttributes:
                  key: otherAttributes
              - conceptLink: conceptLink
                appInfo: appInfo
                value: value
                otherAttributes:
                  key: otherAttributes
              appinfo: appinfo
            uri: uri
            valueProperty: valueProperty
          pattern: pattern
        documentation:
        - lang: lang
          value: value
        - lang: lang
          value: value
        attributeList:
          attribute:
          - conceptLink: conceptLink
            valueScheme: BOOLEAN
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            name: name
            attributeValueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            otherAttributes:
              key: otherAttributes
            required: true
            autoValue:
            - autoValue
            - autoValue
          - conceptLink: conceptLink
            valueScheme: BOOLEAN
            documentation:
            - lang: lang
              value: value
            - lang: lang
              value: value
            name: name
            attributeValueScheme:
              vocabulary:
                valueLanguage: valueLanguage
                enumeration:
                  item:
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  - conceptLink: conceptLink
                    appInfo: appInfo
                    value: value
                    otherAttributes:
                      key: otherAttributes
                  appinfo: appinfo
                uri: uri
                valueProperty: valueProperty
              pattern: pattern
            otherAttributes:
              key: otherAttributes
            required: true
            autoValue:
            - autoValue
            - autoValue
        name: name
        cardinalityMin:
        - cardinalityMin
        - cardinalityMin
        valueSchemeAttribute: BOOLEAN
        cardinalityMax:
        - cardinalityMax
        - cardinalityMax
        otherAttributes:
          key: otherAttributes
        multilingual: true
        autoValue:
        - autoValue
        - autoValue
      properties:
        documentation:
          items:
            $ref: "#/components/schemas/DocumentationType"
          type: array
          xml:
            name: Documentation
        attributeList:
          $ref: "#/components/schemas/AttributeListType"
        valueScheme:
          $ref: "#/components/schemas/ValueSchemeType"
        autoValue:
          items:
            type: string
            xml:
              name: AutoValue
          type: array
          xml:
            name: AutoValue
        name:
          type: string
          xml:
            attribute: true
        conceptLink:
          type: string
          xml:
            attribute: true
            name: ConceptLink
        cardinalityMin:
          items:
            type: string
          type: array
          xml:
            attribute: true
            name: CardinalityMin
        cardinalityMax:
          items:
            type: string
          type: array
          xml:
            attribute: true
            name: CardinalityMax
        multilingual:
          type: boolean
          xml:
            attribute: true
            name: Multilingual
        otherAttributes:
          additionalProperties:
            type: string
        valueSchemeAttribute:
          enum:
          - BOOLEAN
          - DECIMAL
          - FLOAT
          - INT
          - STRING
          - ANY_URI
          - DATE
          - G_DAY
          - G_MONTH
          - G_YEAR
          - TIME
          - DATE_TIME
          type: string
          xml:
            attribute: true
            name: ValueScheme
    EnumerationType:
      example:
        item:
        - conceptLink: conceptLink
          appInfo: appInfo
          value: value
          otherAttributes:
            key: otherAttributes
        - conceptLink: conceptLink
          appInfo: appInfo
          value: value
          otherAttributes:
            key: otherAttributes
        appinfo: appinfo
      properties:
        appinfo:
          type: string
        item:
          items:
            $ref: "#/components/schemas/ItemType"
          type: array
      required:
      - item
    Header:
      example:
        successor: successor
        name: name
        derivedFrom: derivedFrom
        description: description
        id: id
        statusComment: statusComment
        status: status
      properties:
        id:
          type: string
          xml:
            name: ID
        name:
          type: string
          xml:
            name: Name
        description:
          type: string
          xml:
            name: Description
        status:
          type: string
          xml:
            name: Status
        statusComment:
          type: string
          xml:
            name: StatusComment
        successor:
          type: string
          xml:
            name: Successor
        derivedFrom:
          type: string
          xml:
            name: DerivedFrom
      required:
      - id
      - name
      - status
    ItemType:
      example:
        conceptLink: conceptLink
        appInfo: appInfo
        value: value
        otherAttributes:
          key: otherAttributes
      properties:
        value:
          type: string
        conceptLink:
          type: string
          xml:
            attribute: true
            name: ConceptLink
        appInfo:
          type: string
          xml:
            attribute: true
            name: AppInfo
        otherAttributes:
          additionalProperties:
            type: string
    ValueSchemeType:
      example:
        vocabulary:
          valueLanguage: valueLanguage
          enumeration:
            item:
            - conceptLink: conceptLink
              appInfo: appInfo
              value: value
              otherAttributes:
                key: otherAttributes
            - conceptLink: conceptLink
              appInfo: appInfo
              value: value
              otherAttributes:
                key: otherAttributes
            appinfo: appinfo
          uri: uri
          valueProperty: valueProperty
        pattern: pattern
      properties:
        pattern:
          type: string
        vocabulary:
          $ref: "#/components/schemas/VocabularyType"
    VocabularyType:
      example:
        valueLanguage: valueLanguage
        enumeration:
          item:
          - conceptLink: conceptLink
            appInfo: appInfo
            value: value
            otherAttributes:
              key: otherAttributes
          - conceptLink: conceptLink
            appInfo: appInfo
            value: value
            otherAttributes:
              key: otherAttributes
          appinfo: appinfo
        uri: uri
        valueProperty: valueProperty
      properties:
        enumeration:
          $ref: "#/components/schemas/EnumerationType"
        uri:
          type: string
          xml:
            attribute: true
            name: URI
        valueProperty:
          type: string
          xml:
            attribute: true
            name: ValueProperty
        valueLanguage:
          type: string
          xml:
            attribute: true
            name: ValueLanguage
    ComponentDescription:
      example:
        successor: successor
        creatorName: creatorName
        description: description
        derivedfrom: derivedfrom
        userId: userId
        recommended: true
        groupName: groupName
        public: true
        commentsCount: 0
        domainName: domainName
        name: name
        registrationDate: 2000-01-23T04:56:07.000+00:00
        isPublic: true
        href: href
        id: id
        showInEditor: true
        status: development
      properties:
        name:
          type: string
        description:
          type: string
        registrationDate:
          format: date-time
          type: string
        creatorName:
          type: string
        userId:
          type: string
        domainName:
          type: string
        href:
          type: string
          xml:
            namespace: http://www.w3.org/1999/xlink
        groupName:
          type: string
        status:
          enum:
          - development
          - production
          - deprecated
          type: string
        derivedfrom:
          type: string
        successor:
          type: string
        commentsCount:
          format: int32
          type: integer
        recommended:
          type: boolean
        public:
          type: boolean
        id:
          type: string
        showInEditor:
          type: boolean
        isPublic:
          type: boolean
      xml:
        name: componentDescription
    ComponentsList:
      example:
        components:
        - successor: successor
          creatorName: creatorName
          description: description
          derivedfrom: derivedfrom
          userId: userId
          recommended: true
          groupName: groupName
          public: true
          commentsCount: 0
          domainName: domainName
          name: name
          registrationDate: 2000-01-23T04:56:07.000+00:00
          isPublic: true
          href: href
          id: id
          showInEditor: true
          status: development
        - successor: successor
          creatorName: creatorName
          description: description
          derivedfrom: derivedfrom
          userId: userId
          recommended: true
          groupName: groupName
          public: true
          commentsCount: 0
          domainName: domainName
          name: name
          registrationDate: 2000-01-23T04:56:07.000+00:00
          isPublic: true
          href: href
          id: id
          showInEditor: true
          status: development
      properties:
        components:
          items:
            $ref: "#/components/schemas/ComponentDescription"
          type: array

